### ISSUE TITLE
The google 2 way sync is not showing in daily view and it is showing in monthly view

### ISSUE THREAD

**Issue by saifali40** [Setmore2018/Setmore_IssueRepository#13]
> <div class="intercom-container"><img src="https://downloads.intercomcdn.com/i/o/43262243/1f67ba378d0801ce20ea8bc4/Screen+Shot+2017-12-21+at+3.48.45+AM.png"></div><div class="intercom-container"><img src="https://downloads.intercomcdn.com/i/o/43262244/9c8468dc372952b77ecb694c/Screen+Shot+2017-12-21+at+3.49.29+AM.png"></div>

**Link:** [Conversation with Mark](https://app.intercom.com/a/apps/xhnn6n6y/respond/inbox/all/conversations/13660821942)

**Customer:** [Mark](https://app.intercom.com/a/apps/xhnn6n6y/users/55eaa02f94259bf11700db3b/all-conversations) from [RAD Computers](https://app.intercom.com/a/apps/xhnn6n6y/companies/55eaa02f94259bf11700db3c)
**Customer ID:** 28f9d582-af7a-4087-b6b8-0e167e50eff1
**Company ID:** 28f9d582-af7a-4087-b6b8-0e167e50eff1
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xhnn6n6y/respond/inbox/all/conversations/13660821942) when this issue is closed.

**Comment by priyapurushothaman** [comment]
@saifali40 Multiday event will not work in Setmore. He needs to create Allday event for those days. If he created the multi-day event that is visible only on the monthly view of the calendar in Setmore. And it will block only the first day. It will not block rest of the days. 
https://docs.google.com/document/d/17aefwHGyje7QNvqIu0-rEjuKT_xPwnI8FrDNP6ooZ5k/edit
Check this document once.

**Comment by saifali40** [comment]
@PriyaPurushothaman 
customer is confusing with that, the event is showing in monthly but not in daily and it is not blocking on those days.

**Comment by priyapurushothaman** [comment]
Yes, please explain this to the customer. We already discussed with @mo.

**Comment by priyapurushothaman** [comment]
We need to do some structural changes. Now, this is not possible to do. So closing this one/
