### ISSUE TITLE
Calendar issue

### ISSUE THREAD

**Issue by Setmore2018** [Setmore2018/Setmore_IssueRepository#2]
Calendar page getting slow
https://app.intercom.io/a/apps/xhnn6n6y/respond/inbox/unassigned/conversations/13297171131

**Comment by Setmore2018** [comment]
Test comment

**Comment by Setmore2018** [comment]
Issue fixed

**Comment by RevathiBala** [comment]
test

**Comment by RevathiBala** [comment]
test
