### ISSUE TITLE
Payment Issue

### ISSUE THREAD

**Issue by udhaya21** [Setmore2018/Setmore_IssueRepository#8]
https://app.intercom.io/a/apps/xhnn6n6y/respond/inbox/725694/conversations/13397492316

**Comment by udhaya21** [comment]
Billing History not loading

**Comment by udhaya21** [comment]
Issue Fixed reply back to the customer.

**Comment by priyapurushothaman** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Example title that describes bug.](https://trello.com/c/ee9md4S6/212-example-title-that-describes-bug)
