### ISSUE TITLE
Problem in updating card details in Safari Browser

### ISSUE THREAD

**Issue by udhaya21** [Setmore2018/Setmore_IssueRepository#9]
> Hey im trying to update my card information and when I click update card details nothing happens

**Link:** [Conversation with Erin Withers](https://app.intercom.com/a/apps/xhnn6n6y/respond/inbox/all/conversations/13316921267)

**Customer:** [Erin Withers](https://app.intercom.com/a/apps/xhnn6n6y/users/565f5d96874a1a7f03000528/all-conversations) from [Stylist & Co Hair Designs](https://app.intercom.com/a/apps/xhnn6n6y/companies/565f5d97b94d2aeab6000493)
**Customer ID:** 2cd4008bcd7747a7e323a7011ca66ff068d5ae07
**Company ID:** 2cd4008bcd7747a7e323a7011ca66ff068d5ae07
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/xhnn6n6y/respond/inbox/all/conversations/13316921267) when this issue is closed.

**Comment by udhaya21** [comment]
https://app.intercom.io/a/apps/xhnn6n6y/respond/inbox/664931/conversations/13115191621
Same problem for another customer.

**Comment by RevathiBala** [comment]
We need to do some functionality changes for browser kind of issues. We make a note of it. Will work on this. Now am closing this chat
